[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  '@pwnednomore/contracts/=lib/pnm-contracts/',
  'forge-std/=lib/forge-std/src/',
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  'tranche/=lib/tranche/contracts/',
  '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
]
# eth_rpc_url = "https://eth.llamarpc.com"
block_number = 16833213
verbosity = 4

[rpc_endpoints]
mainnet = "https://eth.llamarpc.com"

[etherscan]
mainnet = { key = "4SVWAWDTMDDTHWWPUU1VHN2NBDAE7M8BR6" }

[profile.dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs" }
# See more config options https://github.com/foundry-rs/foundry/tree/master/config