[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  '@pwnednomore/contracts/=lib/pnm-contracts/',
  'forge-std/=lib/forge-std/src/',
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  'tranche/=lib/tranche/contracts/'
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config